version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    # ignore heroicons as for some reason it errors out
    ignore:
      - dependency-name: "heroicons"
