import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :music_listings, MusicListingsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :sentry,
  dsn:
    "https://8c7ceb60f5020b593d1e040668028796@o4510755347824640.ingest.us.sentry.io/4510755351035904",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  release: System.get_env("SENTRY_RELEASE") || System.get_env("RENDER_GIT_COMMIT"),
  traces_sample_rate: 1.0,
  integrations: [
    telemetry: [
      report_handler_failures: true
    ]
  ]

config :music_listings, :logger, [
  {:handler, :my_sentry_handler, Sentry.LoggerHandler,
   %{
     config: %{
       metadata: [:file, :line],
       rate_limiting: [max_events: 10, interval: _1_second = 1_000],
       capture_log_messages: true
     }
   }}
]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
